package IHM;


import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import CODE.*; // importe tout le package
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Léo Philippon
 */
public class InterfaceEquipement extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceEquipement
     */
    public InterfaceEquipement() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        supprimerMachine = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        modifierMachine = new javax.swing.JButton();
        Fiabilité = new javax.swing.JButton();

        jLabel1.setText("référence");

        jLabel2.setText("désignation");

        jLabel3.setText("type");

        jLabel4.setText("coût");

        jLabel5.setText("abscisse");

        jLabel6.setText("ordonée");

        jLabel7.setText("durée");

        jLabel8.setText("état");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jButton1.setText("Créer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("référence");

        jLabel10.setText("désignation");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jButton3.setText("Créer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jRadioButton1.setText(Equipement.affichageMachine(1)
        );

        jRadioButton2.setText(Equipement.affichageMachine(2)
        );

        jRadioButton3.setText(Equipement.affichageMachine(3));

        jRadioButton4.setText(Equipement.affichageMachine(4));

        jRadioButton5.setText(Equipement.affichageMachine(5));

        jRadioButton6.setText(Equipement.affichageMachine(6));

        jRadioButton7.setText(Equipement.affichageMachine(7));

        jRadioButton8.setText(Equipement.affichageMachine(8));

        jRadioButton9.setText(Equipement.affichageMachine(9));

        jRadioButton10.setText(Equipement.affichageMachine(10));

        jRadioButton11.setText(Equipement.affichageMachine(11));

        jRadioButton12.setText(Equipement.affichageMachine(12));

        jLabel11.setText("Machines ("+Equipement.nombreMachines()+"/12)");

        jLabel12.setText("Créer Machine :");

        jLabel13.setText("Créer poste :");

        jLabel14.setText("console");

        supprimerMachine.setText("Supprimer la ou les machines séléctionées");
        supprimerMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerMachineActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel15.setText("Equipement");

        jPanel1.setBackground(new java.awt.Color(187, 187, 187));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        modifierMachine.setText("Modifier la machine séléctionée");
        modifierMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierMachineActionPerformed(evt);
            }
        });

        Fiabilité.setText("Fiabilité");
        Fiabilité.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiabilitéActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField1)
                                            .addComponent(jTextField2)
                                            .addComponent(jTextField3)
                                            .addComponent(jTextField4)
                                            .addComponent(jTextField5)
                                            .addComponent(jTextField6)
                                            .addComponent(jTextField7)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supprimerMachine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifierMachine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fiabilité, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supprimerMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modifierMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(Fiabilité))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Machine.setMachine(jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText(),jTextField7.getText(),jTextField8.getText());  
            // TODO add your handling code here:
            if (Machine.setMachine(jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText(),jTextField7.getText(),jTextField8.getText())==0){jLabel14.setText("La machine a été crée !");}
            if (Machine.setMachine(jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText(),jTextField7.getText(),jTextField8.getText())==1){jLabel14.setText("erreur type : manuelle ou numérique !");}
            if (Machine.setMachine(jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText(),jTextField7.getText(),jTextField8.getText())==2){jLabel14.setText("erreur état : HS ou S !");}
            if (Machine.setMachine(jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText(),jTextField7.getText(),jTextField8.getText())==3){jLabel14.setText("cout, durée, abscisse et ordonée doivent être des nombres réels !");}
           
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);     
        }
        jRadioButton1.setText(Equipement.affichageMachine(1)); // =reinitialisation des boutons dans le coté postes pour que ce soit plus facile

        jRadioButton2.setText(Equipement.affichageMachine(2));

        jRadioButton3.setText(Equipement.affichageMachine(3));

        jRadioButton4.setText(Equipement.affichageMachine(4));

        jRadioButton5.setText(Equipement.affichageMachine(5));

        jRadioButton6.setText(Equipement.affichageMachine(6));

        jRadioButton7.setText(Equipement.affichageMachine(7));

        jRadioButton8.setText(Equipement.affichageMachine(8));

        jRadioButton9.setText(Equipement.affichageMachine(9));

        jRadioButton10.setText(Equipement.affichageMachine(10));

        jRadioButton11.setText(Equipement.affichageMachine(11));

        jRadioButton12.setText(Equipement.affichageMachine(12));
        
        jLabel11.setText("Machines ("+Equipement.nombreMachines()+"/12)"); // reinitialise le nbr de machine 
        try {
            File fiabilitémachine = new File(Atelier.lien()+"Equipement/Fiabilité/"+(jTextField1.getText())+".txt");
             if (!(fiabilitémachine.exists())){
             Fiabilite.addTimeMachine(jTextField1.getText());}
            if (Equipement.paramètreMachine(jTextField1.getText()+"("+jTextField2.getText()+").txt","état").equals("HS")){Fiabilite.panneMachine(jTextField1.getText(),jTextField2.getText());}
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //création du poste contenant les machines séléctionnées 
        //on créé le poste grâce à la méthode setPoste
        
        try {
            Poste.setPoste(jTextField9.getText(), jTextField10.getText());        // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
         if ((jRadioButton1.isSelected()==true)&&(!(jRadioButton1.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton1.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         if ((jRadioButton2.isSelected()==true)&&(!(jRadioButton2.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton2.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if ((jRadioButton3.isSelected()==true)&&(!(jRadioButton3.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton3.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if ((jRadioButton4.isSelected()==true)&&(!(jRadioButton4.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton4.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if ((jRadioButton5.isSelected()==true)&&(!(jRadioButton5.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton5.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if ((jRadioButton6.isSelected()==true)&&(!(jRadioButton6.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton6.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if ((jRadioButton7.isSelected()==true)&&(!(jRadioButton7.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton7.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if ((jRadioButton8.isSelected()==true)&&(!(jRadioButton8.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton8.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if ((jRadioButton9.isSelected()==true)&&(!(jRadioButton9.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton9.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if ((jRadioButton10.isSelected()==true)&&(!(jRadioButton10.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton10.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if ((jRadioButton11.isSelected()==true)&&(!(jRadioButton11.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton11.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         if ((jRadioButton12.isSelected()==true)&&(!(jRadioButton12.getText().equals("vide")))){try {
             Poste.addMachine(jTextField9.getText(), jTextField10.getText(),jRadioButton12.getText());
            } catch (IOException ex) {
                Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
         
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    Poste.supPoste(jTextField9.getText(),jTextField10.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void supprimerMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerMachineActionPerformed
    // Méthode permettant la suppression de machine, si un boutton est selectionné, on supprimme la machine associée à ce dernier.
    //à la fin de la méthode, on remmet à jour le titre de tous les bouttons 
        
     if ((jRadioButton1.isSelected()==true)&&(!(jRadioButton1.getText().equals("vide")))){
         Machine.supMachine(jRadioButton1.getText());
     }
     if ((jRadioButton2.isSelected()==true)&&(!(jRadioButton2.getText().equals("vide")))){
         Machine.supMachine(jRadioButton2.getText());
     }
     if ((jRadioButton3.isSelected()==true)&&(!(jRadioButton3.getText().equals("vide")))){
         Machine.supMachine(jRadioButton3.getText());
     }
     if ((jRadioButton4.isSelected()==true)&&(!(jRadioButton4.getText().equals("vide")))){
         Machine.supMachine(jRadioButton4.getText());
     }
     if ((jRadioButton5.isSelected()==true)&&(!(jRadioButton5.getText().equals("vide")))){
         Machine.supMachine(jRadioButton5.getText());
     }
     if ((jRadioButton6.isSelected()==true)&&(!(jRadioButton6.getText().equals("vide")))){
         Machine.supMachine(jRadioButton6.getText());
     }
     if ((jRadioButton7.isSelected()==true)&&(!(jRadioButton7.getText().equals("vide")))){
         Machine.supMachine(jRadioButton7.getText());
     }
     if ((jRadioButton8.isSelected()==true)&&(!(jRadioButton8.getText().equals("vide")))){
         Machine.supMachine(jRadioButton8.getText());
     }
     if ((jRadioButton9.isSelected()==true)&&(!(jRadioButton9.getText().equals("vide")))){
         Machine.supMachine(jRadioButton9.getText());
     }
     if ((jRadioButton10.isSelected()==true)&&(!(jRadioButton10.getText().equals("vide")))){
         Machine.supMachine(jRadioButton10.getText());
     }
     if ((jRadioButton11.isSelected()==true)&&(!(jRadioButton11.getText().equals("vide")))){
         Machine.supMachine(jRadioButton11.getText());
     }
     if ((jRadioButton12.isSelected()==true)&&(!(jRadioButton12.getText().equals("vide")))){
         Machine.supMachine(jRadioButton12.getText());
     }
     
     

        // Actualisation du titre des bouttons 
        jRadioButton1.setText(Equipement.affichageMachine(1));

        jRadioButton2.setText(Equipement.affichageMachine(2));

        jRadioButton3.setText(Equipement.affichageMachine(3));

        jRadioButton4.setText(Equipement.affichageMachine(4));

        jRadioButton5.setText(Equipement.affichageMachine(5));

        jRadioButton6.setText(Equipement.affichageMachine(6));

        jRadioButton7.setText(Equipement.affichageMachine(7));

        jRadioButton8.setText(Equipement.affichageMachine(8));

        jRadioButton9.setText(Equipement.affichageMachine(9));

        jRadioButton10.setText(Equipement.affichageMachine(10));

        jRadioButton11.setText(Equipement.affichageMachine(11));

        jRadioButton12.setText(Equipement.affichageMachine(12));// TODO add your handling code here:
        
        // Actualisation du nombre de machines
        jLabel11.setText("Machines ("+Equipement.nombreMachines()+"/12)");
        
        jLabel14.setText("machine(s) supprimées");
        
    }//GEN-LAST:event_supprimerMachineActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void modifierMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierMachineActionPerformed
   //Méthode permettant de modifier une machine, lorsqu'un bouton est selectioné, on va chercher tous les paramètres de la machine selectionée (jRadioButton(x).getText())
   //en utilisant la fonction paramètreMachine de la classe Equipement, ces parametres sont alors affiché dans les jTextField où l'utilisateur va pouvoir les modifier
   //à la fin de la méthode, on supprime la machine pour éviter d'avoir plusieurs fois la même machine avec seulement un paramètre différent
   
        if ((jRadioButton1.isSelected()==true)&&(!(jRadioButton1.getText().equals("vide")))){
        try {
            String machine = jRadioButton1.getText();
            jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        } 
        if ((jRadioButton2.isSelected()==true)&&(!(jRadioButton2.getText().equals("vide")))){
        try {
            String machine = jRadioButton2.getText();
            jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            Machine.supMachine(machine);
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if ((jRadioButton3.isSelected()==true)&&(!(jRadioButton3.getText().equals("vide")))){
        try {
            String machine = jRadioButton3.getText();
            jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if ((jRadioButton4.isSelected()==true)&&(!(jRadioButton4.getText().equals("vide")))){
        try {
            String machine = jRadioButton4.getText();
           jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if ((jRadioButton5.isSelected()==true)&&(!(jRadioButton5.getText().equals("vide")))){
        try {
            String machine = jRadioButton5.getText();
            jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if ((jRadioButton6.isSelected()==true)&&(!(jRadioButton6.getText().equals("vide")))){
        try {
            String machine = jRadioButton6.getText();
           jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if ((jRadioButton7.isSelected()==true)&&(!(jRadioButton7.getText().equals("vide")))){
        try {
            String machine = jRadioButton7.getText();
            jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if ((jRadioButton8.isSelected()==true)&&(!(jRadioButton8.getText().equals("vide")))){
        try {
            String machine = jRadioButton8.getText();
           jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if ((jRadioButton9.isSelected()==true)&&(!(jRadioButton9.getText().equals("vide")))){
        try {
            String machine = jRadioButton9.getText();
           jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if ((jRadioButton10.isSelected()==true)&&(!(jRadioButton10.getText().equals("vide")))){
        try {
            String machine = jRadioButton10.getText();
            jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if ((jRadioButton11.isSelected()==true)&&(!(jRadioButton11.getText().equals("vide")))){
        try {
            String machine = jRadioButton11.getText();
           jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        if ((jRadioButton12.isSelected()==true)&&(!(jRadioButton12.getText().equals("vide")))){
        try {
            String machine = jRadioButton12.getText();
           jTextField1.setText(Equipement.paramètreMachine(machine,"dMachine"));
            jTextField2.setText(Equipement.paramètreMachine(machine,"refMachine"));
            jTextField3.setText(Equipement.paramètreMachine(machine,"type"));
            jTextField4.setText(Equipement.paramètreMachine(machine,"coût"));
            jTextField5.setText(Equipement.paramètreMachine(machine,"abscisse"));
            jTextField6.setText(Equipement.paramètreMachine(machine,"ordonnée"));
            jTextField7.setText(Equipement.paramètreMachine(machine,"durée"));
            jTextField8.setText(Equipement.paramètreMachine(machine,"état"));
            
        } catch (IOException ex) {
            Logger.getLogger(InterfaceEquipement.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
   
    }//GEN-LAST:event_modifierMachineActionPerformed

    private void FiabilitéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiabilitéActionPerformed
    
			
				                         
                            new FiabilitéInterface().setVisible(true);
			
    }//GEN-LAST:event_FiabilitéActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceEquipement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceEquipement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceEquipement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceEquipement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceEquipement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fiabilité;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton modifierMachine;
    private javax.swing.JButton supprimerMachine;
    // End of variables declaration//GEN-END:variables
}
